# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
  nginx:
    # используем последний стабильный образ nginx
    image: nginx:latest
    # маршрутизируем порты
    ports:
      - "8089:80"
      - "443:443"
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs/nginx:/var/log/nginx
    # nginx должен общаться с php контейнером
    links:
      - php
  php:
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: images/php
    # этот образ будет общаться с mysql
    links:
      - postgres
    # монтируем директорию с проектами
    volumes:
      - ./www:/var/www

  postgres:

    image: postgres:13.3

    environment:
      POSTGRES_DB: "contact_list_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Qwerty12"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /datapgsql:/docker-entrypoint-initdb.d
      - /pgsqlFiles:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3.7.5-management
    working_dir: /www
    hostname: rabbit-mq
    container_name: 'rabbit-mq'
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: my_vhost