monolog:
    handlers:
        stream_debug:
            type: stream
            path: "%kernel.logs_dir%/debug.log"
            level: debug
            channels: [ "!event" ]

        stream_error:
            type: stream
            path: "%kernel.logs_dir%/error.log"
            level: error
            channels: [ "!event" ]
        stream_telegram:
            type: service
            id: Monolog\Handler\TelegramBotHandler
