# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    EfTech\ContactList\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    EfTech\ContactList\Entity\RecipientRepositoryInterface:
        factory: [ '@Doctrine\ORM\EntityManagerInterface', 'getRepository' ]
        arguments:
            $entityName: EfTech\ContactList\Entity\Recipient
    EfTech\ContactList\Entity\CustomerRepositoryInterface:
        factory: [ '@Doctrine\ORM\EntityManagerInterface', 'getRepository' ]
        arguments:
            $entityName: EfTech\ContactList\Entity\Customer
    EfTech\ContactList\Entity\ColleagueRepositoryInterface:
        factory: [ '@Doctrine\ORM\EntityManagerInterface', 'getRepository' ]
        arguments:
            $entityName: EfTech\ContactList\Entity\Colleague
    EfTech\ContactList\Entity\KinsfolkRepositoryInterface:
        factory: [ '@Doctrine\ORM\EntityManagerInterface', 'getRepository' ]
        arguments:
            $entityName: EfTech\ContactList\Entity\Kinsfolk
    EfTech\ContactList\Entity\ContactListRepositoryInterface:
        factory: [ '@Doctrine\ORM\EntityManagerInterface', 'getRepository' ]
        arguments:
            $entityName: EfTech\ContactList\Entity\ContactList
    EfTech\ContactList\Entity\AddressRepositoryInterface:
        factory: [ '@Doctrine\ORM\EntityManagerInterface', 'getRepository' ]
        arguments:
            $entityName: EfTech\ContactList\Entity\Address
    EfTech\ContactList\Entity\UserRepositoryInterface:
        factory: [ '@Doctrine\ORM\EntityManagerInterface', 'getRepository' ]
        arguments:
            $entityName: EfTech\ContactList\Entity\User
    EfTech\ContactList\DoctrineEventSubscriber\EntityEventSubscriber:
        tags:
            - name: 'doctrine.event_subscriber'
    Monolog\Handler\TelegramBotHandler:
        arguments:
            $apiKey: '%env(TELEGRAM_BOT_KEY)%'
            $channel: '%env(TELEGRAM_CHANAL)%'
            $level: 'error'